format = '''

$username@$hostname $os $directory$all$time $shell$cmd_duration $character'''

add_newline = false

[character]
success_symbol = "[âœ ](bold green)"
error_symbol = "[âœ• ](bold red)"
vimcmd_symbol = "[âœ ](bold green)"

[directory]
disabled = false
truncation_length = 8
truncation_symbol = 'â€¦/'
truncate_to_repo = false

[cmd_duration]
disabled = false
min_time = 2000
format = ' [took $duration](bold red)'

[git_branch]
ignore_branches = []

[hostname]
ssh_only = false
format = '[$ssh_symbol](bold blue)[$hostname](bold red)'
disabled = false

[os]
disabled = false

[os.symbols]
Arch = 'ğŸ§'
Artix = 'ğŸ§'

[shell]
disabled = false
bash_indicator = 'bash'
format = '[\($indicator\)](bold blue)'

[time]
disabled = false
time_format = '%R'
format = 'ğŸ•™ [$time]($style)'

[username]
disabled = false
show_always = true
format = '[$user]($style)'

[aws]
disabled = true

[azure]
disabled = true

[gcloud]
disabled = true

[singularity]
disabled = true
